### ISSUE TITLE
Missing theme on project detail page

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#672] opened 2022-06-21 12:57 UTC
https://kohesio.test.ec.europa.eu/en/projects?theme=Sustainable-and-quality-employment&sort=Total-Budget-(descending)

when starting from this link and clicking a project, the related icon does not display and we have a kind default ion (electric bulb) instead

**Comment by madewild** [comment] 2022-06-21 13:24
The problem is not really the icon, it's because the theme is marked as n/a on the detail page instead of "Sustainable and quality employment".

@DiaZork can you check why themeLabels and themeIds are empty on https://kohesio.test.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q3936213 ?

on https://linkedopendata.eu/wiki/Item:Q3936213 there is an intervention field https://linkedopendata.eu/wiki/Item:Q200742 so the theme info should be in the project api

**Comment by D063520** [comment] 2022-06-23 16:54
Is solved. The problem was that the TO was only retrieved from the entity directly and not as a fallback also form the intervention field.

**Closed by D063520** 2022-06-23 16:54 UTC
Labels: bug

**Comment by gachpas** [comment] 2022-06-24 07:02
Thanks @D063520 ;)
