### ISSUE TITLE
small css problem

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#756] opened 2022-11-30 09:31 UTC
<img width="317" alt="Screenshot 2022-11-30 at 10 29 44" src="https://user-images.githubusercontent.com/10883585/204759131-c96d6642-79d1-4713-8988-59e93635cba9.png">

**Comment by madewild** [comment] 2022-12-05 14:53
Duplicate of #754

**Closed by madewild** 2022-12-05 14:53 UTC
