### ISSUE TITLE
Allow searching by clicking on terms in project detail page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#536] opened 2022-02-20 06:48 UTC
It would be nice if users were able to see the results by theme, intervention field and program by clicking on these items also from the project detail page.

**Comment by madewild** [comment] 2022-02-21 14:18
reported by @roberto-musmeci 
fyi @AThollard (also reported by other user)

**Comment by madewild** [comment] 2022-05-16 09:29
@AThollard @roberto-musmeci please discuss internally and let us know what to implement
postponed to 1.3 anyway

**Comment by madewild** [comment] 2022-08-24 13:57
@AThollard in the end should we go for this or not? Not too difficult on our side, more a matter of business decision :)

**Comment by AThollard** [comment] 2022-08-24 14:20
Intervention field and program definitly yes. Themes are more problematic as we might change them in the future. Let me discuss this with @roberto-musmeci on Monday.

**Comment by madewild** [comment] 2022-08-24 14:24
@raphdom we could already do a test with intervention field and/or programme

**Comment by raphdom** [comment] 2022-09-01 08:09
Yes I can, but on the project detail API can I have the intervention field ID and programme label and ID? @DiaZork?

**Comment by madewild** [comment] 2022-09-08 09:59
@D063520 @DiaZork could you add this? it's blocking another issue :)

**Comment by D063520** [comment] 2022-09-16 09:39
I added it ...

<img width="1724" alt="Screenshot 2022-09-16 at 11 39 20" src="https://user-images.githubusercontent.com/10883585/190607869-c0d5d2dc-368a-4333-ac62-b263b2908400.png">

**Comment by raphdom** [comment] 2022-09-19 08:21
Okay, now is good for THEME and INTERVENTION FIELD. For programs we need to decide where I should put the link, can you check it @madewild ?

**Comment by madewild** [comment] 2022-09-19 08:25
@roberto-musmeci currently on https://kohesio.development.ec.europa.eu/en/projects/Q100952 if we click on the programme name "Lubuskie Voivodeship" we jump to the programme page https://ec.europa.eu/regional_policy/EN/atlas/programmes/2014-2020/poland/2014PL16M2OP004

Do we want to keep this behaviour or allow searching over a programme inside Kohesio by clicking? Difficult to keep both...

**Comment by roberto-musmeci** [comment] 2022-09-19 09:17
What do you think if we place the link to the InfoRegio page in a hyperlink that displays 
_"read further about the investment program"_
and if we click on the program name we jump to the project list filtered by that specific program ? 

Basically as we do for "_read further about the project_"

**Comment by madewild** [comment] 2022-09-19 09:19
Yes something like this...

**Comment by raphdom** [comment] 2022-09-20 07:55
Can you check on dev, please? @madewild @roberto-musmeci 
https://kohesio.development.ec.europa.eu/en/projects/Q100952
The problem is, the program label that we have on project detail is not the same that we have in the filters, 
@D063520 don't know if you can add the first part of the programme label that I can concatenate?

**Comment by roberto-musmeci** [comment] 2022-09-20 07:59
thanks @raphdom. The functionality works perfectly. 
Could you move the string "read further about the investment program" at the bottom of the _funding_ box to align it with the layout of the _project info_ box
![image](https://user-images.githubusercontent.com/86654885/191201369-b6b8af20-6920-49bb-a688-3615cbbe4498.png)

**Comment by madewild** [comment] 2022-09-20 08:00
I would style it like this:
![read_further](https://user-images.githubusercontent.com/942488/191201306-ccc0ca2f-b12c-4581-90d9-c756329a9ae9.png)

With the same vertical spacing as before "Read further about the project"

**Comment by madewild** [comment] 2022-09-20 08:00
Great minds... ;)

**Comment by raphdom** [comment] 2022-09-20 09:30
done, just waiting @D063520 about the programme label value

**Comment by D063520** [comment] 2022-09-20 09:32
@raphdom : what you want exactly, the QID?

**Comment by raphdom** [comment] 2022-09-20 09:34
For this example:
https://kohesio.development.ec.europa.eu/en/projects/Q100952
I have programmeLabel: Lubuskie Voivodeship
And in the filters the value of this programme is: 2014PL16M2OP004 - Lubuskie Voivodeship

**Comment by D063520** [comment] 2022-09-20 09:37
I would prefer to use IDs like here:

https://kohesio.development.ec.europa.eu/api/facet/eu/search/project?offset=0&limit=15&country=https://linkedopendata.eu/entity/Q13&program=https://linkedopendata.eu/entity/Q2463421&orderTotalBudget=false

instead of labels. Also because the labels can change and they are language dependent .....

**Comment by D063520** [comment] 2022-09-20 09:44
So we will render in the project view also "2014PL16M2OP004 - Lubuskie Voivodeship"?

**Comment by raphdom** [comment] 2022-09-20 09:45
You can send me the programmeFullLabel, maybe? it is too difficult?

**Comment by D063520** [comment] 2022-09-20 09:47
it's that the query starts looking like this:

<img width="1046" alt="Screenshot 2022-09-20 at 11 46 50" src="https://user-images.githubusercontent.com/10883585/191226065-5b84f82a-d622-4315-ab0c-ddf774bfefbe.png">

(and this is only a part)

**Comment by raphdom** [comment] 2022-09-20 10:49
Now is good, we can close it, thanks @D063520

**Closed by raphdom** 2022-09-20 10:49 UTC
Labels: enhancement
