### ISSUE TITLE
sometimes projects of beneficiaries not rendered even if API came back

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#579] opened 2022-02-24 14:21 UTC
<img width="1680" alt="Screenshot 2022-02-24 at 15 18 35" src="https://user-images.githubusercontent.com/10883585/155541506-2db0a941-838b-49fa-b001-9cebbc5d71c7.png">

I can reproduce it by clicking on some of this list of beneficiaries

https://kohesio.development.ec.europa.eu/beneficiaries?page=3&name=water&country=Italy

**Comment by madewild** [comment] 2022-02-24 14:24
I tried to reproduce but cannot...

**Comment by D063520** [comment] 2022-02-24 14:26
on how many beneficiaries did you click?

**Comment by madewild** [comment] 2022-02-24 14:27
5 or 6

there is no page 3 so I guess you mean https://kohesio.development.ec.europa.eu/beneficiaries?name=water&country=Italy

**Comment by madewild** [comment] 2022-02-24 14:28
I tried to reproduce but cannot...

There is no page 3 so I guess you mean https://kohesio.development.ec.europa.eu/beneficiaries?name=water&country=Italy

**Comment by madewild** [comment] 2022-02-24 14:29
Ah no I have it! You need to open several in a row, OK.

**Comment by D063520** [comment] 2022-02-24 14:29
you run into the other bug also : )

**Comment by D063520** [comment] 2022-02-24 14:30
> Ah no I have it! You need to open several in a row, OK.

I think if the request is fast (which is the case when it is cached) it is not appearing. But if it is a bit slower the UI is not triggering the rerendering

**Comment by madewild** [comment] 2022-02-24 14:31
https://kohesio.development.ec.europa.eu/beneficiaries/Q4196129
![ben1](https://user-images.githubusercontent.com/942488/155543868-ed2394cc-ee47-49f2-9658-146ee2df4dcb.png)

https://kohesio.development.ec.europa.eu/beneficiaries/Q4205743
![ben2](https://user-images.githubusercontent.com/942488/155543911-610bd0f6-40d2-4c9c-9f9b-da5268677160.png)

**Comment by madewild** [comment] 2022-02-24 14:35
(separate issue I think)

**Comment by madewild** [comment] 2022-02-24 14:36
Notice that the "Graph" and "More" buttons are also badly rendered in the screenshots... Something is blocking part of the response.

**Comment by raphdom** [comment] 2022-02-24 15:34
in fact we have 2 bugs here, the last one is fixed with the other issue (https://github.com/ec-doris/kohesio-frontend/issues/581) and the pagination error, I can reproduce it if I go to here: https://kohesio.development.ec.europa.eu/beneficiaries?name=water&country=Italy&page=2 and change the page in the url to here: https://kohesio.development.ec.europa.eu/beneficiaries?name=water&country=Italy&page=3. We can control it but not in this version, for 1.2

**Comment by madewild** [comment] 2022-02-24 15:35
Sure, the bigger problem is the other one (data not displayed)

**Comment by madewild** [comment] 2022-02-24 15:36
Sure, the bigger problem is the other one (data not displayed)

**Comment by madewild** [comment] 2022-02-24 15:36
Sure, the bigger problem is the other one (data not displayed)

**Comment by madewild** [comment] 2022-02-24 15:46
@raphdom this sounds like a serious bug... you don't think we can fix it for 1.1?

**Comment by raphdom** [comment] 2022-02-24 15:50
let me check the complexity of this, because we don't have the total in the first place, we need to wait the call to check if the page index match...

**Comment by madewild** [comment] 2022-02-24 15:57
No Raph, this is not the important issue.
Look at the screenshots: we are missing the list of projects, the EU contribution, the funds...

**Closed** 2022-02-24 16:01 UTC
Labels: bug

**Comment by D063520** [comment] 2022-02-24 16:36
looks fine ....
