### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#242] opened 2021-07-12 14:01 UTC
I am not sure if the requirements have changed through time, as I was not involved in the last months but, initially, the global search was supposed to search on all ements, while the ones specific to projects and beneficiarries were looking only on the category in reference.

If you look for a beneficiary in the global search, you do not find it.

Please ignore if the requirements have changed ;o)

**Comment by madewild** [comment] 2021-07-12 14:04
The problem is: which page should we open when we search? we cannot know in advance if people will search for a project or a beneficiary... Or a separate page just for these global search results? Then we need a design (wireframe) for this...

**Comment by madewild** [comment] 2021-07-12 14:04
@AThollard what do you think?

**Comment by gachpas** [comment] 2021-07-12 14:08
@madewild , well it could be a global search with possibility of filtering...it is what one expect from a search that is on the top and present on all the pages
but, as said, it was mentioned in the beginning and is maybe not part anymore of the requirements...

**Comment by AThollard** [comment] 2021-07-12 14:39
It was indeed the initial requirement, even to be able to search on a region's name.
After 1.5 years of intensive usage, we could even challenge the 'global search' itself. Personally at this stage I don't see the added value. 
I would open one or several  tickets for the UI evolution for the final launch
1) Global search / keep it or not? OR add filters (I am not really in favor of this option / redundant with the projects and beneficiaries button)
2) Caroussel get rid of it? keep it for highlighted projects?
3) Themes: add digital in addition to green?
4) Map: align with standard EU maps... (separated issue)
We could test the end-users in MSs on these specific questions ? @slaven777 @Bisiaam 
Also what are the trends in UI design about global search bar? @teodoracostin @raphdom

**Comment by gachpas** [comment] 2021-07-12 14:42
@madewild , do we need to review the mobile version now?
While looking a bit, I see some elements, which used to work properly and which are now not fully OK...

**Comment by madewild** [comment] 2021-07-12 14:43
FYI, this is already an issue for the final launch, see tag "v1.0 milestone" ;)

**Comment by madewild** [comment] 2021-12-20 09:55
@D063520 does the backend support searching on projects AND beneficiaries at the same time?
If yes it's a matter of adding a special page to display the Google-like results over everything...

**Comment by D063520** [comment] 2021-12-20 10:00
Yes, this is possible

**Comment by madewild** [comment] 2021-12-20 10:25
OK cool so @raphdom can move ahead

**Comment by raphdom** [comment] 2022-01-31 09:46
@D063520 it is possible, good, but it is already implemented? There is an endpoint to get both mixed?

**Comment by D063520** [comment] 2022-01-31 12:00
it is possible, but this is not for milestone 1, no?

**Comment by madewild** [comment] 2022-01-31 12:26
Well yes it was planned for this milestone, requested since July... ;)
But we can postpone to 1.1 if you need more time
@gachpas @AThollard  what's the degree of urgency?

**Comment by D063520** [comment] 2022-01-31 15:04
Jonathan will create an API for this ....

**Comment by madewild** [comment] 2022-02-02 10:45
@DiaZork when do you expect to have this ready?

**Comment by DiaZork** [comment] 2022-02-02 12:45
Here is a first version : https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/general?offset=0&limit=15&keywords=fire

It's quite slow when it's not cached for the moment but i'm looking into it

**Comment by madewild** [comment] 2022-02-02 12:52
@prototorpedo could you prepare a draft result page. You can check with @raphdom for the requirements...

**Comment by DiaZork** [comment] 2022-02-02 13:43
The speed is a lot better now !

**Comment by madewild** [comment] 2022-02-11 13:51
Maybe we can reuse something of this component: https://digital-strategy.ec.europa.eu/en/search?search=regions

**Comment by madewild** [comment] 2022-02-16 06:34
Skeleton is there: https://kohesio.development.ec.europa.eu/search?keywords=wifi
So now it's a matter of getting the results from https://kohesio.development.ec.europa.eu/api/facet/eu/search/general?offset=0&limit=15&keywords=wifi and arranging the cards like on https://digital-strategy.ec.europa.eu/en/search?search=wifi

**Comment by DiaZork** [comment] 2022-02-21 14:16
I've add everything

**Comment by madewild** [comment] 2022-02-21 14:21
Excellent, @raphdom can you check if you have all the elements you need for the card?

**Comment by raphdom** [comment] 2022-02-21 16:06
Thanks @DiaZork. Now we have the first version of the global search. @madewild and @D063520 can you check please?

**Comment by raphdom** [comment] 2022-02-21 16:06
on dev

**Comment by madewild** [comment] 2022-02-21 16:18
Nice first version!
@raphdom some summaries are missing although they are provided by the API
I think you cut long summaries with "..." but then for some reason the summaries shorter than the threshold are not displayed ;)
@gachpas can you also test?

**Comment by madewild** [comment] 2022-02-21 16:19
![Uploading summary_missing.png…]()

**Comment by raphdom** [comment] 2022-02-21 16:20
indeed, my bad, already fixed. 2min to deploy :)

**Comment by madewild** [comment] 2022-02-21 16:20
PS: I tried to disable the ugly purple for visited links in most pages by adding

```css
a:visited {
    color: #004494;
}
```

**Comment by raphdom** [comment] 2022-02-21 16:22
this is something that came with ECL:
https://ec.europa.eu/component-library/ec/components/navigation/link/code/

**Comment by madewild** [comment] 2022-02-21 16:23
I know, but I hate it! Looks like IE from the nineties ;)

**Comment by madewild** [comment] 2022-02-21 16:26
Note for @DiaZork : the general search is quite slow, maybe we could put a limit at 5000 results like for the others...

**Comment by madewild** [comment] 2022-02-21 17:08
(I opened a separate issue on the backend side for this)

**Comment by madewild** [comment] 2022-02-21 17:15
@AThollard @roberto-musmeci can you also test the global search on dev and provide feedback?

**Comment by roberto-musmeci** [comment] 2022-02-22 10:09
@AThollard  and I discussed briefly. Overall, it seems to work fine. I will keep on testing it today. 

One changes we would like to propose is to highlight more the type of the result (project vs beneficiary)
Currently it's a but hard to distinguish beneficiaries from projects. We though about including a clear text on top of the EU Flag. This is just a suggestion. Definitely open to more ideas @madewild  :)  

![image](https://user-images.githubusercontent.com/86654885/155109677-dd4a6dda-501e-444e-b963-30f5719d71ab.png)

Anyway, we should change the label from "Kohesio project" to "project"

**Comment by AThollard** [comment] 2022-02-22 10:24
Can you please add the pagination at the top of the results list  (for now only displayed at the bottom)

**Comment by AThollard** [comment] 2022-02-22 11:04
I have tested it both on mobile and desktop, everything seems to work fine on my side.
Possible enhancement: the flag on the mobile version is really big, maybe reduce it a bit.

**Comment by madewild** [comment] 2022-02-22 11:23
I would not put text above the flag. Maybe use a different default image for beneficiaries?
The "Kohesio project" comes straight from the Wikibase (instance of). @raphdom can you fix it in the frontend or do we need to change in the backend?

**Comment by raphdom** [comment] 2022-02-22 12:38
@madewild , @AThollard , @roberto-musmeci @gachpas:  I did some improvements:
- Pagination on top and bottom
- Decrease the image size on mobile
- Normalize "Project" or "Beneficiary" label

on dev

**Comment by madewild** [comment] 2022-02-22 13:03
Great! @AThollard do you want a different image for project/beneficiary or good enough like this?

**Comment by AThollard** [comment] 2022-02-22 13:30
Do you have a different image or we have to find one?

**Comment by madewild** [comment] 2022-02-22 13:33
we need to find one...

**Comment by AThollard** [comment] 2022-02-22 13:34
OK, I check quickly in the EC audiovisual service catalogue

**Comment by madewild** [comment] 2022-02-22 13:37
If you find one for project and one for beneficiary even better... The flag was just a default and does not particulary match either. ;)

**Comment by AThollard** [comment] 2022-02-22 13:39
ok

**Comment by AThollard** [comment] 2022-02-22 14:25
Not that easy and not a lot of choic
For beneficiary: 
![image](https://user-images.githubusercontent.com/80402472/155149768-c5778d50-38b4-4042-8f2c-28ebe4a30090.png)
![P051516-189895](https://user-images.githubusercontent.com/80402472/155151766-7fa42d00-2fa2-44b7-a018-5b25a53cc44e.jpg)

what do you think @roberto-musmeci @madewild

**Comment by AThollard** [comment] 2022-02-22 14:26
If no one is convinced, we keep the flag!

**Comment by roberto-musmeci** [comment] 2022-02-22 14:34
> I like the first one! :) The second one will be a bit too much if we display 15 times on a page (+ free ad for iPhone!!)

The picture is nice but as it is associated to "beneficiaries" it may be seen as people putting their hands to receive EU money :/ ahah I don't think it is the best way to portrait beneficiaries ahah 

Trying to find some more options also from my side

**Comment by AThollard** [comment] 2022-02-22 14:35
Indeed and instead of money they receive a star ;-)

**Comment by AThollard** [comment] 2022-02-22 14:37
![istockphoto-1134037713-612x612](https://user-images.githubusercontent.com/80402472/155154111-e59af4b9-44d1-4d6a-a521-6b04bbbf31b5.jpg)
Also this one for projects

**Comment by madewild** [comment] 2022-02-22 14:45
Please decide still today so that @raphdom can implement in DEV and merge to TEST and ACC tomorrow...

**Comment by Bisiaam** [comment] 2022-02-22 14:47
My proposal : 
![image](https://user-images.githubusercontent.com/85291854/155155693-c9716961-ded7-468d-9537-f72b03de79ff.png)

**Comment by AThollard** [comment] 2022-02-22 14:51
Projects
![image](https://user-images.githubusercontent.com/80402472/155157479-4f70ab41-b1e5-4e9b-9b62-b816b2538d6e.png)

**Comment by AThollard** [comment] 2022-02-22 14:54
I prefer the handshake, there was a version more neutral without the ring. Can you find it on the AV portal please @Bisiaam ?

**Comment by Bisiaam** [comment] 2022-02-22 14:56
Yes here: https://audiovisual.ec.europa.eu/en/reportage/P-039364

![image](https://user-images.githubusercontent.com/85291854/155158309-5edfcead-7e62-4b54-b022-3afd0d21c5c8.png)
![image](https://user-images.githubusercontent.com/85291854/155158418-da071aaf-f694-47ef-aaf7-f92a78f35632.png)

**Comment by roberto-musmeci** [comment] 2022-02-22 15:01
So EU flag for project and handshake for beneficiaries ? 
Handshake 1 or 2 ? In the second one, the woman's hand is a bit weird, no ?

**Comment by Bisiaam** [comment] 2022-02-22 15:06
I would say the first picture (with the lady, I don't think the ring would be a problem), but if you prefer let's take the first handshake (indeed the woman's hand is a bit weird).

**Comment by AThollard** [comment] 2022-02-22 15:09
Ok, then let's go for the handshake with the ring for beneficiaries (I think also the flag colors will match more) and the flag for projects

**Comment by madewild** [comment] 2022-02-22 15:59
OK, @raphdom can you take care of that?

**Comment by raphdom** [comment] 2022-02-22 16:19
I will

**Comment by AThollard** [comment] 2022-02-22 17:44
Nice. Thanks @raphdom

**Comment by madewild** [comment] 2022-02-22 19:18
Great:

![global_fixed](https://user-images.githubusercontent.com/942488/155203098-8b228783-efcc-43d3-82d6-b54c97264427.png)

Closing for now, next round of improvements for 1.2 :)

**Closed by madewild** 2022-02-22 19:18 UTC
Labels: enhancement
